package service

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

func NewBootstrapToken() (string, error) {
	buf := make([]byte, 24)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func BuildClientOVPN(remoteHost string, port int, certCN string, proto string) []byte {
	p := NormalizeInstanceProto(proto)
	hdr := OpenVPNClientProfileHeader(remoteHost, port, p)
	content := hdr + fmt.Sprintf(`

# Placeholder profile generated by control plane.
# cert_cn: %s
# TODO: integrate real certificate material from agent/easy-rsa.
`, certCN)
	return []byte(content)
}
